"""make lesson teacher optional and add teacher to result

Revision ID: 1271601eeb5a
Revises: 7b185b8ab327
Create Date: 2025-12-07 18:18:50.317589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1271601eeb5a"
down_revision: Union[str, Sequence[str], None] = "7b185b8ab327"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lesson", "teacher_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column(
        "scheduleresult", sa.Column("teacher_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "scheduleresult", "teacher", ["teacher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scheduleresult", type_="foreignkey")
    op.drop_column("scheduleresult", "teacher_id")
    op.alter_column("lesson", "teacher_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
