"""Add Project model and link to Lesson

Revision ID: 1482cf11f222
Revises:
Create Date: 2025-12-07 05:03:33.626811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1482cf11f222"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "studentgroupcourselink",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["studentgroup.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "course_id"),
    )
    op.add_column(
        "course", sa.Column("units", sa.Integer(), nullable=False, server_default="2")
    )
    op.add_column("course", sa.Column("min_population", sa.Integer(), nullable=True))
    op.add_column("course", sa.Column("max_population", sa.Integer(), nullable=True))
    op.add_column("lesson", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "lesson", "project", ["project_id"], ["id"])

    # Create Enum type explicitly
    weekparity_enum = sa.Enum("ODD", "EVEN", "BOTH", name="weekparity")
    weekparity_enum.create(op.get_bind())

    op.add_column(
        "scheduleresult",
        sa.Column(
            "week_parity", weekparity_enum, nullable=False, server_default="BOTH"
        ),
    )
    op.add_column(
        "studentgroup",
        sa.Column("allowed_days", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studentgroup", "allowed_days")
    op.drop_column("scheduleresult", "week_parity")
    op.drop_constraint(None, "lesson", type_="foreignkey")
    op.drop_column("lesson", "project_id")
    op.drop_column("course", "max_population")
    op.drop_column("course", "min_population")
    op.drop_column("course", "units")
    op.drop_table("studentgroupcourselink")
    op.drop_table("project")
    # ### end Alembic commands ###
