"""update_models_remove_accessibility_field_term_id

Revision ID: 6cbadda81053
Revises: 9fd12cb1effa
Create Date: 2025-12-07 17:39:59.980601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbadda81053'
down_revision: Union[str, Sequence[str], None] = '9fd12cb1effa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom', 'accessibility_features')
    op.drop_constraint(op.f('studentgroup_entrance_term_id_fkey'), 'studentgroup', type_='foreignkey')
    op.drop_column('studentgroup', 'entrance_term_id')
    op.drop_column('studentgroup', 'field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentgroup', sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('studentgroup', sa.Column('entrance_term_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('studentgroup_entrance_term_id_fkey'), 'studentgroup', 'entranceterm', ['entrance_term_id'], ['id'])
    op.add_column('classroom', sa.Column('accessibility_features', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
