"""add name and description to project

Revision ID: 7b185b8ab327
Revises: 4739583bb5f8
Create Date: 2025-12-07 18:06:45.347216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7b185b8ab327"
down_revision: Union[str, Sequence[str], None] = "4739583bb5f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="New Project",
        ),
    )
    op.add_column(
        "project",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("project", "term_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("project", "term_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("project", "description")
    op.drop_column("project", "name")
    # ### end Alembic commands ###
