"""refactor_teacher_availability

Revision ID: 9fd12cb1effa
Revises: 2e6c50b0cecd
Create Date: 2025-12-07 13:58:24.901259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd12cb1effa'
down_revision: Union[str, Sequence[str], None] = '2e6c50b0cecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'available_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('available_slots', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
