"""add_timestamps_to_models

Revision ID: ab427cdeef3d
Revises: f1e2d3c4b5a6
Create Date: 2025-12-07 19:27:33.368749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab427cdeef3d"
down_revision: Union[str, Sequence[str], None] = "f1e2d3c4b5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classroom",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "classroom",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "course",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "course",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # op.alter_column('scheduleresult', 'teacher_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.add_column(
        "studentgroup",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "studentgroup",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "teacher",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "teacher",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teacher", "updated_at")
    op.drop_column("teacher", "created_at")
    op.drop_column("studentgroup", "updated_at")
    op.drop_column("studentgroup", "created_at")
    op.alter_column(
        "scheduleresult", "teacher_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("course", "updated_at")
    op.drop_column("course", "created_at")
    op.drop_column("classroom", "updated_at")
    op.drop_column("classroom", "created_at")
    # ### end Alembic commands ###
