"""add_timestamps_to_project

Revision ID: c1b07cdca296
Revises: ab427cdeef3d
Create Date: 2025-12-07 19:41:55.338353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1b07cdca296"
down_revision: Union[str, Sequence[str], None] = "ab427cdeef3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # op.alter_column('scheduleresult', 'teacher_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scheduleresult", "teacher_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("project", "updated_at")
    op.drop_column("project", "created_at")
    # ### end Alembic commands ###
